<#
    Removes regenerable build output and installed dependencies from the
    OpenISave 2.0 development folder.

        powershell -ExecutionPolicy Bypass -File .\scripts\clean_build_artifacts.ps1
        powershell -ExecutionPolicy Bypass -File .\scripts\clean_build_artifacts.ps1 -DryRun

    Only the explicit paths listed below are removed. Source code, migrations,
    tests, docs, scripts, icons, logo.png and lockfiles are never touched, and
    nothing under %LOCALAPPDATA%\OpenISave2 (the real financial data, backups
    and logs) is ever considered.

    Everything removed here is rebuilt by:
        backend   py -3.11 -m venv .venv; pip install -r requirements-dev.txt
        frontend  npm ci
        root      npm ci                (Tauri CLI)
        desktop   scripts\package_windows.ps1
#>
[CmdletBinding()]
param(
    # List what would be removed without deleting anything.
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Split-Path -Parent $PSScriptRoot)).Path.TrimEnd('\')

# Explicit, project-relative targets. No wildcards.
$targets = @(
    'desktop\target',               # Rust / Tauri build output, incl. installer bundle
    'desktop\binaries',             # backend sidecar staged for bundling
    'desktop\gen',                  # schemas generated by tauri-build
    'backend\.venv',                # Python virtual environment
    'backend\build',                # PyInstaller work directory
    'backend\dist',                 # PyInstaller output
    'backend\.pytest_cache',
    'backend\.ruff_cache',
    'backend\.mypy_cache',
    'backend\htmlcov',
    'backend\.coverage',
    'backend\coverage.xml',
    'frontend\node_modules',        # npm dependencies (incl. .vite cache)
    'frontend\dist',                # Vite production build
    'frontend\coverage',
    'frontend\tsconfig.tsbuildinfo',
    'node_modules',                 # root Tauri CLI
    '.pytest_cache'
)

# __pycache__ folders are only searched for inside these backend source roots.
$pycacheRoots = @('backend', 'backend\app', 'backend\alembic', 'backend\tests')

# Hard guard: the user's data directory must never be inside a target.
$userData = if ($env:LOCALAPPDATA) { (Join-Path $env:LOCALAPPDATA 'OpenISave2').TrimEnd('\') } else { $null }

function Get-FolderBytes([string]$path) {
    if (-not (Test-Path -LiteralPath $path)) { return [int64]0 }
    $item = Get-Item -LiteralPath $path -Force
    if (-not $item.PSIsContainer) { return [int64]$item.Length }
    $sum = [int64]0
    foreach ($file in [System.IO.Directory]::EnumerateFiles($path, '*', [System.IO.SearchOption]::AllDirectories)) {
        try { $sum += (New-Object System.IO.FileInfo $file).Length } catch { }
    }
    return $sum
}

function Format-Size([int64]$bytes) {
    if ($bytes -ge 1GB) { return '{0:N2} GB' -f ($bytes / 1GB) }
    return '{0:N1} MB' -f ($bytes / 1MB)
}

function Assert-SafeTarget([string]$full) {
    $full = $full.TrimEnd('\')
    if (-not $full.StartsWith($root + '\', [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to delete outside the project: $full"
    }
    if ($userData -and ($full.StartsWith($userData, [System.StringComparison]::OrdinalIgnoreCase) -or
                        $userData.StartsWith($full, [System.StringComparison]::OrdinalIgnoreCase))) {
        throw "Refusing to touch the OpenISave user data directory: $full"
    }
}

function Remove-Target([string]$full) {
    Assert-SafeTarget $full
    $item = Get-Item -LiteralPath $full -Force
    if (-not $item.PSIsContainer) {
        Remove-Item -LiteralPath $full -Force
        return
    }
    # A junction or symlink is removed as a link; its target is never followed.
    if ($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
        [System.IO.Directory]::Delete($full, $false)
        return
    }
    # rmdir /s does not traverse junctions inside the tree and copes with the
    # long paths found in node_modules.
    cmd /c "rmdir /s /q `"$full`"" | Out-Null
    if (Test-Path -LiteralPath $full) { throw "Could not fully remove $full (is a program still using it?)" }
}

$before = Get-FolderBytes $root

$found = New-Object System.Collections.Generic.List[string]
foreach ($relative in $targets) {
    $full = Join-Path $root $relative
    if (Test-Path -LiteralPath $full) { $found.Add($full) }
}
foreach ($relative in $pycacheRoots) {
    $base = Join-Path $root $relative
    if (-not (Test-Path -LiteralPath $base)) { continue }
    # Direct children only for 'backend' so the (already listed) .venv is not scanned.
    $recurse = $relative -ne 'backend'
    Get-ChildItem -LiteralPath $base -Directory -Force -Filter '__pycache__' -Recurse:$recurse -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -notmatch '\\\.venv\\' } |
        ForEach-Object { if (-not $found.Contains($_.FullName)) { $found.Add($_.FullName) } }
}

Write-Host ''
Write-Host "Project: $root" -ForegroundColor Cyan
Write-Host "Before:  $(Format-Size $before)" -ForegroundColor Cyan
Write-Host ''

if ($found.Count -eq 0) {
    Write-Host 'Nothing to clean.' -ForegroundColor Green
    exit 0
}

foreach ($full in $found) {
    Assert-SafeTarget $full
    $size = Get-FolderBytes $full
    $relative = $full.Substring($root.Length + 1)
    if ($DryRun) {
        Write-Host ('  would remove  {0,-40} {1,10}' -f $relative, (Format-Size $size)) -ForegroundColor Yellow
    } else {
        Write-Host ('  removing      {0,-40} {1,10}' -f $relative, (Format-Size $size)) -ForegroundColor Yellow
        Remove-Target $full
    }
}

$after = Get-FolderBytes $root
Write-Host ''
if ($DryRun) {
    Write-Host 'Dry run: nothing was deleted.' -ForegroundColor Green
} else {
    Write-Host "Before: $(Format-Size $before)" -ForegroundColor Green
    Write-Host "After:  $(Format-Size $after)" -ForegroundColor Green
    Write-Host "Freed:  $(Format-Size ($before - $after))" -ForegroundColor Green
}
