<#
    Removes regenerable build output and installed dependencies from the
    OpenISave 2.0 development folder.

        powershell -ExecutionPolicy Bypass -File .\scripts\clean_build_artifacts.ps1
        powershell -ExecutionPolicy Bypass -File .\scripts\clean_build_artifacts.ps1 -DryRun

    Only the explicit paths listed below (plus __pycache__ folders) are removed.
    Safe to re-run at any time. Source code, migrations, tests, docs, scripts,
    icons, logo.png, lockfiles, .git and release\ are never touched, and
    nothing under %LOCALAPPDATA%\OpenISave2Data (the encrypted vault, backups
    and logs) or %LOCALAPPDATA%\OpenISave2 (2.0.x plaintext data) is ever
    considered.

    Everything removed here is rebuilt by:
        backend   py -3.11 -m venv .venv; pip install -r requirements-dev.txt
        frontend  npm ci
        root      npm ci                (Tauri CLI)
        desktop   scripts\package_windows.ps1
#>
[CmdletBinding()]
param(
    # List what would be removed without deleting anything.
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Split-Path -Parent $PSScriptRoot)).Path.TrimEnd('\')

# Explicit, project-relative targets. No wildcards.
$targets = @(
    'desktop\target',               # Rust / Tauri build output, incl. installer bundle
    'desktop\binaries',             # backend sidecar staged for bundling
    'desktop\gen',                  # schemas generated by tauri-build
    'backend\.venv',                # Python virtual environment
    'backend\build',                # PyInstaller work directory
    'backend\dist',                 # PyInstaller output
    'backend\.pytest_cache',
    'backend\.ruff_cache',
    'backend\.mypy_cache',
    'backend\htmlcov',
    'backend\.coverage',
    'backend\coverage.xml',
    'frontend\node_modules',        # npm dependencies (incl. .vite cache)
    'frontend\dist',                # Vite production build
    'frontend\coverage',
    'frontend\tsconfig.tsbuildinfo',
    'frontend\tsconfig.node.tsbuildinfo',
    'frontend\.vite',               # Vite dep cache when cacheDir is outside node_modules
    'frontend\.eslintcache',
    'node_modules',                 # root Tauri CLI
    '.pytest_cache',
    '.ruff_cache',
    '.mypy_cache'
)

# __pycache__ folders are searched for across the whole project, skipping
# these directories (either protected or already removed as a whole).
$pycacheSkipDirs = @('.git', 'release', 'node_modules', '.venv', 'target', 'binaries', 'build', 'dist')

# Never deleted, even if a target above ever came to point at or into them.
$protectedRelative = @('.git', 'release', 'backend\app', 'backend\alembic', 'backend\tests',
                       'frontend\src', 'desktop\src', 'docs', 'scripts')

# Hard guard: the user's data directories must never be inside a target.
# (The 'OpenISave2' prefix also covers 'OpenISave2Data'; both are listed so
# the protection does not depend on that coincidence.)
$userDataDirs = @()
if ($env:LOCALAPPDATA) {
    $userDataDirs += (Join-Path $env:LOCALAPPDATA 'OpenISave2Data').TrimEnd('\')
    $userDataDirs += (Join-Path $env:LOCALAPPDATA 'OpenISave2').TrimEnd('\')
}

function Get-FolderBytes([string]$path) {
    if (-not (Test-Path -LiteralPath $path)) { return [int64]0 }
    $item = Get-Item -LiteralPath $path -Force
    if (-not $item.PSIsContainer) { return [int64]$item.Length }
    $sum = [int64]0
    foreach ($file in [System.IO.Directory]::EnumerateFiles($path, '*', [System.IO.SearchOption]::AllDirectories)) {
        try { $sum += (New-Object System.IO.FileInfo $file).Length } catch { }
    }
    return $sum
}

function Format-Size([int64]$bytes) {
    if ($bytes -ge 1GB) { return '{0:N2} GB' -f ($bytes / 1GB) }
    return '{0:N1} MB' -f ($bytes / 1MB)
}

function Assert-SafeTarget([string]$full) {
    $full = $full.TrimEnd('\')
    if (-not $full.StartsWith($root + '\', [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to delete outside the project: $full"
    }
    $leaf = Split-Path -Leaf $full
    foreach ($relative in $protectedRelative) {
        $protected = Join-Path $root $relative
        # Refuse the protected folder itself, anything containing it, and anything
        # inside it other than a __pycache__ folder.
        if ($protected.StartsWith($full + '\', [System.StringComparison]::OrdinalIgnoreCase) -or
            $protected.Equals($full, [System.StringComparison]::OrdinalIgnoreCase) -or
            ($full.StartsWith($protected + '\', [System.StringComparison]::OrdinalIgnoreCase) -and $leaf -ne '__pycache__')) {
            throw "Refusing to touch protected project path: $full"
        }
    }
    foreach ($userData in $userDataDirs) {
        if ($full.StartsWith($userData, [System.StringComparison]::OrdinalIgnoreCase) -or
            $userData.StartsWith($full, [System.StringComparison]::OrdinalIgnoreCase)) {
            throw "Refusing to touch the OpenISave user data directory: $full"
        }
    }
}

function Remove-Target([string]$full) {
    Assert-SafeTarget $full
    $item = Get-Item -LiteralPath $full -Force
    if (-not $item.PSIsContainer) {
        Remove-Item -LiteralPath $full -Force
        return
    }
    # A junction or symlink is removed as a link; its target is never followed.
    if ($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
        [System.IO.Directory]::Delete($full, $false)
        return
    }
    # rmdir /s does not traverse junctions inside the tree and copes with the
    # long paths found in node_modules.
    cmd /c "rmdir /s /q `"$full`"" | Out-Null
    if (Test-Path -LiteralPath $full) { throw "Could not fully remove $full (is a program still using it?)" }
}

$before = Get-FolderBytes $root

$found = New-Object System.Collections.Generic.List[string]
foreach ($relative in $targets) {
    $full = Join-Path $root $relative
    if (Test-Path -LiteralPath $full) { $found.Add($full) }
}
# Manual walk so skipped trees (node_modules, .venv, target, ...) are never entered.
$pending = New-Object System.Collections.Generic.Stack[string]
$pending.Push($root)
while ($pending.Count -gt 0) {
    foreach ($dir in [System.IO.Directory]::GetDirectories($pending.Pop())) {
        $name = Split-Path -Leaf $dir
        if ($pycacheSkipDirs -contains $name) { continue }
        if ((Get-Item -LiteralPath $dir -Force).Attributes -band [System.IO.FileAttributes]::ReparsePoint) { continue }
        if ($name -eq '__pycache__') {
            if (-not $found.Contains($dir)) { $found.Add($dir) }
        } else {
            $pending.Push($dir)
        }
    }
}

Write-Host ''
Write-Host "Project: $root" -ForegroundColor Cyan
Write-Host "Before:  $(Format-Size $before)" -ForegroundColor Cyan
Write-Host ''

if ($found.Count -eq 0) {
    Write-Host 'Nothing to clean.' -ForegroundColor Green
    exit 0
}

foreach ($full in $found) {
    Assert-SafeTarget $full
    $size = Get-FolderBytes $full
    $relative = $full.Substring($root.Length + 1)
    if ($DryRun) {
        Write-Host ('  would remove  {0,-40} {1,10}' -f $relative, (Format-Size $size)) -ForegroundColor Yellow
    } else {
        Write-Host ('  removing      {0,-40} {1,10}' -f $relative, (Format-Size $size)) -ForegroundColor Yellow
        Remove-Target $full
    }
}

$after = Get-FolderBytes $root
Write-Host ''
if ($DryRun) {
    Write-Host 'Dry run: nothing was deleted.' -ForegroundColor Green
} else {
    Write-Host "Before: $(Format-Size $before)" -ForegroundColor Green
    Write-Host "After:  $(Format-Size $after)" -ForegroundColor Green
    Write-Host "Freed:  $(Format-Size ($before - $after))" -ForegroundColor Green
}
