import { theme as antdTheme, type ThemeConfig } from 'antd';

import type { ResolvedTheme } from './appearance';
import { paletteFor } from './palette';

/**
 * Ant Design theme for one mode. Dark starts from the official dark
 * algorithm and then pins OpenISave's own surfaces, text and accent on top,
 * so AntD's derived colours (hover fills, dropdowns, pickers) stay in family
 * rather than drifting to AntD's stock greys.
 */
const FONT =
  "'Segoe UI Variable Text', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'PingFang SC', " +
  "'Microsoft YaHei', Roboto, Helvetica, Arial, sans-serif";

export function createTheme(mode: ResolvedTheme): ThemeConfig {
  const p = paletteFor(mode);
  const dark = mode === 'dark';

  return {
    algorithm: dark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
    cssVar: false,
    token: {
      colorPrimary: p.primary,
      colorLink: p.accentText,
      colorLinkHover: dark ? '#a3bcf8' : p.primaryHover,
      colorLinkActive: p.primaryActive,
      colorSuccess: p.positive,
      colorError: p.negative,
      colorWarning: p.warning,
      colorInfo: p.primary,
      colorText: p.text,
      colorTextSecondary: p.muted,
      colorTextTertiary: p.subtle,
      colorTextQuaternary: dark ? '#5a6372' : '#a4abb7',
      colorTextPlaceholder: p.subtle,
      colorBgLayout: p.bg,
      colorBgContainer: p.surface,
      colorBgElevated: dark ? p.raised : p.surface,
      colorBgSpotlight: dark ? '#262c38' : '#1b2130',
      colorBgMask: p.mask,
      colorBorder: p.border,
      colorBorderSecondary: p.borderSoft,
      colorFill: dark ? 'rgba(255, 255, 255, 0.08)' : 'rgba(20, 26, 41, 0.07)',
      colorFillSecondary: dark ? 'rgba(255, 255, 255, 0.06)' : '#f1f3f6',
      colorFillTertiary: dark ? 'rgba(255, 255, 255, 0.04)' : '#f4f5f8',
      colorFillQuaternary: dark ? 'rgba(255, 255, 255, 0.025)' : '#f8f9fb',
      colorSplit: p.borderSoft,
      controlItemBgHover: dark ? 'rgba(255, 255, 255, 0.05)' : '#f3f5f8',
      controlItemBgActive: p.primarySoft,
      controlItemBgActiveHover: p.primarySoft,
      controlOutline: p.ring,
      controlOutlineWidth: 3,
      borderRadius: 8,
      borderRadiusLG: 14,
      borderRadiusSM: 6,
      borderRadiusXS: 4,
      controlHeight: 34,
      fontFamily: FONT,
      fontSize: 14,
      lineWidthFocus: 2,
      boxShadow: p.shadowPop,
      boxShadowSecondary: p.shadowPop,
      motionDurationFast: '0.12s',
      motionDurationMid: '0.18s',
      motionDurationSlow: '0.24s',
      motionEaseOut: 'cubic-bezier(0.16, 1, 0.3, 1)',
      motionEaseInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    components: {
      Layout: { siderBg: p.sidebar, bodyBg: p.bg },
      Menu: {
        itemBg: 'transparent',
        itemSelectedBg: p.primarySoft,
        itemSelectedColor: dark ? '#dbe5ff' : '#1f3f9e',
        itemHoverBg: dark ? 'rgba(150, 175, 235, 0.055)' : 'rgba(36, 60, 130, 0.045)',
        itemHoverColor: p.text,
        itemActiveBg: dark ? 'rgba(255, 255, 255, 0.07)' : 'rgba(20, 26, 41, 0.07)',
        itemColor: p.text2,
        itemHeight: 34,
        itemMarginInline: 10,
        itemMarginBlock: 2,
        itemBorderRadius: 8,
        groupTitleColor: p.subtle,
        groupTitleFontSize: 11.5,
        iconSize: 15,
      },
      Card: { paddingLG: 22, headerHeight: 54, headerFontSize: 15, colorBorderSecondary: p.border },
      Button: {
        primaryShadow: 'none',
        defaultShadow: 'none',
        dangerShadow: 'none',
        fontWeight: 500,
        defaultBorderColor: p.border,
        defaultColor: p.text,
        defaultBg: p.surface,
        defaultHoverBg: dark ? '#1d232e' : '#f8f9fb',
        defaultHoverBorderColor: p.borderStrong,
        defaultHoverColor: p.text,
        defaultActiveBg: dark ? '#202733' : '#f1f3f6',
        defaultActiveBorderColor: p.borderStrong,
        defaultActiveColor: p.text,
        textHoverBg: dark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(20, 26, 41, 0.045)',
        paddingInline: 14,
      },
      Input: {
        activeShadow: `0 0 0 3px ${p.ring}`,
        hoverBorderColor: p.borderStrong,
        activeBorderColor: p.primary,
        paddingInline: 11,
      },
      InputNumber: {
        activeShadow: `0 0 0 3px ${p.ring}`,
        hoverBorderColor: p.borderStrong,
        activeBorderColor: p.primary,
      },
      Select: {
        activeOutlineColor: p.ring,
        hoverBorderColor: p.borderStrong,
        activeBorderColor: p.primary,
        optionSelectedBg: p.primarySoft,
        optionSelectedColor: p.text,
        optionActiveBg: dark ? 'rgba(255, 255, 255, 0.05)' : '#f3f5f8',
        optionPadding: '6px 10px',
      },
      DatePicker: {
        activeShadow: `0 0 0 3px ${p.ring}`,
        hoverBorderColor: p.borderStrong,
        activeBorderColor: p.primary,
        cellHoverBg: dark ? 'rgba(255, 255, 255, 0.06)' : '#f1f3f6',
      },
      Table: {
        headerBg: dark ? '#171c25' : '#f9fafb',
        headerColor: p.muted,
        headerSplitColor: 'transparent',
        headerBorderRadius: 0,
        rowHoverBg: dark ? '#191e28' : '#f8f9fb',
        rowSelectedBg: p.primarySoft,
        rowSelectedHoverBg: p.primarySoft,
        rowExpandedBg: dark ? '#131720' : '#fbfbfc',
        borderColor: dark ? '#1b2029' : '#eef0f3',
        cellPaddingBlock: 13,
        cellPaddingBlockMD: 11,
        cellPaddingBlockSM: 8,
        footerBg: p.surface,
      },
      Segmented: {
        trackBg: dark ? '#0f1319' : '#eceef2',
        trackPadding: 3,
        itemSelectedBg: dark ? '#262d39' : '#ffffff',
        itemColor: p.muted,
        itemHoverColor: p.text,
        itemHoverBg: 'transparent',
        itemActiveBg: 'transparent',
        itemSelectedColor: p.text,
      },
      Tag: {
        defaultBg: dark ? 'rgba(255, 255, 255, 0.06)' : '#f1f3f6',
        defaultColor: p.text2,
      },
      Progress: { remainingColor: dark ? '#232a35' : '#edf0f3' },
      Tabs: { itemColor: p.muted, titleFontSize: 14, inkBarColor: p.primary },
      Modal: {
        contentBg: p.surface,
        headerBg: p.surface,
        footerBg: p.surface,
        titleFontSize: 17,
        titleColor: p.text,
      },
      Popover: { titleMinWidth: 180 },
      Tooltip: { paddingSM: 10, paddingXS: 8 },
      Switch: { trackHeight: 22, trackMinWidth: 40, handleSize: 18, trackPadding: 2 },
      Form: {
        itemMarginBottom: 18,
        verticalLabelPadding: '0 0 6px',
        labelColor: p.text2,
        labelFontSize: 13,
      },
      Alert: {
        withDescriptionPadding: '14px 16px',
      },
      Descriptions: { labelBg: 'transparent', titleColor: p.text },
      Message: { contentBg: p.surface, contentPadding: '10px 14px' },
      Notification: { width: 360 },
      Skeleton: {
        gradientFromColor: dark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(20, 26, 41, 0.05)',
        gradientToColor: dark ? 'rgba(255, 255, 255, 0.1)' : 'rgba(20, 26, 41, 0.09)',
      },
    },
  };
}
